name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  migration-validation:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: testing_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_ROOT_PASSWORD: root_password
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=20s
          --health-timeout=10s
          --health-retries=5
          --network-alias=mysql

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, mysql
          coverage: none

      - name: Install Dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
        
      - name: Copy Environment File
        run: |
          cp .env.example .env
          sed -i 's/DB_PORT=3306/DB_PORT=3306/' .env
          sed -i 's/DB_DATABASE=cimb_growthhub_be/DB_DATABASE=testing_db/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=test_user/' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=test_password/' .env
          php artisan key:generate
          php artisan config:cache

      - name: Run Migrations (Up)
        run: php artisan migrate --force
      
      - name: Run Seeder
        run: php artisan db:seed --force

      - name: Run Migrations (Down)
        run: php artisan migrate:rollback --force

      
